### ISSUE TITLE
Name import error

### ISSUE THREAD

**Issue by PeakAudioDevices** [zkSNARK/reddit-auto-reply#1]
Not sure if Comment_forest has been changed since you wrote this, but i get a name import error anytime I try to execute. "ImportError: cannot import name 'Comment' from 'praw.models.comment_forest'" 

And looking at comment_forest.py I don't see any class named Comment. Any idea what I can do here? I have some coding background but never learned python.

There's a real dbag on reddit that I'm tired of replying to so I'm hoping to implement your code and call it a day. Appreciate any help you can provide

**Comment by zkSNARK** [comment]
@PeakAudioDevices Looks like you are right.  A version of this script with the same imports worked at one time in the past, so I presume that something in praw has changed.

**Comment by zkSNARK** [comment]
It appears that the import was only used for type hints.  I'm removing it and pushing now.  I think I see some other issues in the script, but this push should fix this issue.  Feel free to make more issues as you find problems.
