### ISSUE TITLE
This is some kinda bug.  doesn't pass the string into the reply

### ISSUE THREAD

**Issue by zkSNARK** [zkSNARK/reddit-auto-reply#2]
https://github.com/zkSNARK/reddit-auto-reply/blob/4254e7fcdcc6898a9ca2ad2c00454750b1b907d1/reddit_auto_reply.py#L61

**Comment by PeakAudioDevices** [comment]
I get this same error.
TypeError: reply_if_is_target_author() missing 2 required positional arguments: 'target_author' and 'reply'

**Comment by zkSNARK** [comment]
I'll take a look at this later today.  This is part of the recursion, so it is somewhat delicate area.  I'll get it figured out.

**Comment by zkSNARK** [comment]
I believe this is fixed.  I didn't test this though, but I'm guessing it will run now.  Try it out and let me know.

**Comment by PeakAudioDevices** [comment]
Tested and it isnow working!! I might find a way to cycle through responses now. Thank you!!!

**Comment by zkSNARK** [comment]
@PeakAudioDevices thanks for letting me know.  Have you tested it live on reddit?  Cycling (or randomly selecting) from a group of responses would be trivial.  Feel free to submit a PR.

**Comment by PeakAudioDevices** [comment]
I did test it live, it's thrown up the correct comment and downvoted as expected. I'm really unfamiliar with python, what kind of function do you need to cycle through variables like this? I read python has a 'random' function built in, but I have to do more reading to get it implemented. Just from a glance I would probably have to define all the replies and then edit the reply_if_is_target_author( function to pass the correct string based on random's choice

**Comment by zkSNARK** [comment]
Yep, that is generally correct.   Can make the replies in an array, and then cycle through them with a counter and a modulus, or randomize the selected index.  I'll make an issue.
